name: pr-build-and-test
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  on_push:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install packages
        run: |
          npx lerna bootstrap
      - name: Run tests
        run: npx lerna run test
      - name: Collate Coverage Reports
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          for d in ./packages/*/ ; do
              mkdir -p coverage
              if [[ ! -f ${d}/coverage/lcov.info ]]
              then
                  echo "No coverage for ${d}"
                  continue
              fi
              filename="$d""coverage/lcov.info"
              targetSource="SF:""$d""src"
              sed "s|SF:src|$targetSource|g" $filename >> coverage/lcov.info
          done
      - name: Report Coverage
        #Dependabot user will only have read-only perms, so don't try to report coverage
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info